config/routes.rb
Rails.application.routes.draw do
  root to: 'manufacturers#index'
  resources :manufacturers, only: [:index, :new, :create]
  resources :cars, only: [:index, :new, :create]
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :manufacturer_id, presence: true
  validates :color, presence: true
  validates :year, presence: true, numericality:
    { greater_than_or_equal_to: 1920 }
  validates :mileage, presence: true, numericality: { only_integer: true }
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars

  validates :name, presence: true, uniqueness: true
  validates :country, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to cars_path, notice: 'Car created successfully!'
    else
      render "new"
    end
  end

  private

    def car_params
      params.require(:car).permit(:manufacturer_id, :color, :year,
        :mileage, :description)
    end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController

  def index
    @manufacturers = Manufacturer.all
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if @manufacturer.save
      redirect_to manufacturers_path, notice: 'Manufacturer created successfully!'
    else
      render "new"
    end
  end

  private
    def manufacturer_params
      params.require(:manufacturer).permit(:name, :country)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h1>List of Cars</h1>
  <% @cars.each do |car| %>
    <li><%= car.manufacturer.name %>, Color: <%= car.color %>, Year: <%= car.year %>, Mileage: <%= car.mileage %>
    <% unless car.description == "" %>
     Description: <%= car.description %>
    <% end %></li>
  <% end %>
<br>
<%= link_to "Add Car", new_car_path %><br>
<%= link_to "Manufacturer Index", manufacturers_path %>

app/views/cars/new.html.erb
<%= form_for @car do |f| %>

  <% if @car.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@car.errors.count, "error") %> prohibited
      this article from being saved:</h2>

    <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :manufacturer %><br>
    <%= f.collection_select(:manufacturer_id, Manufacturer.all, :id, :name) %>
  </p>

  <p>
    <%= f.label :color %><br>
    <%= f.text_field :color, size: "40x1" %>
  </p>

  <p>
    <%= f.label :year %><br>
    <%= f.date_field :year, size: "10x1" %>
  </p>

  <p>
    <%= f.label :mileage %><br>
    <%= f.number_field :mileage, size: "10x1" %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "40x10" %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back", cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListings</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/manufacturers/index.html.erb
<h1>List of Manufacturers</h1>
  <% @manufacturers.each do |manufacturer| %>
    <li><%= manufacturer.name %> - <%= manufacturer.country %></li>
  <% end %>
<br>
<%= link_to "Add Manufacturer", new_manufacturer_path %><br>
<%= link_to "Car Index", cars_path %>

app/views/manufacturers/new.html.erb
<%= form_for @manufacturer do |f| %>

  <% if @manufacturer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@manufacturer.errors.count, "error") %> prohibited
      this article from being saved:</h2>

    <ul>
      <% @manufacturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :manufacturer %><br>
    <%= f.text_field :name, size: "40x1" %>
  </p>

  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country, size: "40x1" %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back", manufacturers_path %>